name: â™»ï¸ - Check For New Releases

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:

jobs:
  check-releases:
    name: ðŸ“Œ - Check Releases
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify Login
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Release Version
        id: fetch-release-version
        run: |
          curl -sL https://raw.githubusercontent.com/strapi/strapi/main/examples/getstarted/package.json | jq -r ".version" > release/strapi-latest.txt
          echo "VERSION=$(cat release/strapi-latest.txt)" >> $GITHUB_ENV

      - name: Register New Release
        run: |
          git config --global user.email "${{ secrets.MY_GITHUB_EMAIL }}"
          git config --global user.name "${{ github.repository_owner }}"
          git add .
          git commit -m "The latest version of Strapi is: v${{ env.VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}